- docs/usage.md
The `--remove-vcs` option is actually not required, because the package is fetched from Packagist as dist archive.
> [DOCS] Drop recommendation of `--remove-vcs` option

- .gitattributes
- .github/workflows/docker.yaml
- Dockerfile
- README.md
- docker-entrypoint.sh
- docs/usage.md
With this PR, a new Docker image `cpsit/project-builder` is configured. It can be used as an alternative way to the recommended way with Composer.
Usage:
```bash
docker run --rm -it -v <target-dir>:/app cpsit/project-builder
```
> [FEATURE] Build and deploy Docker image for alternative usage

- Dockerfile
Since `composer normalize` is not available during `docker build` and we actually don't really need it, it's removed now.
> [BUGFIX] Do not run `composer normalize` when during `docker build`

- resources/config.schema.json
- src/Builder/Config/ValueObject/CustomizableInterface.php
- src/Builder/Config/ValueObject/SubProperty.php
- src/Builder/Generator/Step/Interaction/SelectInteraction.php
- src/IO/InputReader.php
- src/IO/Messenger.php
- tests/src/Builder/Config/ConfigFactoryTest.php
- tests/src/Builder/Config/ValueObject/SubPropertyTest.php
- tests/src/Builder/Generator/Step/Interaction/QuestionInteractionTest.php
- tests/src/Builder/Generator/Step/Interaction/SelectInteractionTest.php
With this PR, a new config property `properties.*.properties.*.multiple` is introduced. It allows selection of multiple sub-property options.
Example:
```diff
properties:
- identifier: foo
name: Foo
properties:
- identifier: bar
name: Bar
options:
- value: optionA
- value: optionB
- value: optionC
- value: optionD
+        multiple: true
```
> [!!!][FEATURE] Allow selection of multiple sub-property options

- composer.json
- src/Builder/Config/ValueObject/PropertyOption.php
- src/Builder/Generator/Step/CollectBuildInstructionsStep.php
- src/Builder/Generator/Step/Interaction/QuestionInteraction.php
- src/Builder/Generator/Step/Interaction/SelectInteraction.php
Because of https://github.com/advisories/GHSA-5pgm-3j3g-2rc7, the library `cuyz/valinor` is now required in a minimum version of `0.12.0`. With this dependency update, an additional bug concerning supported types in property options is fixed.
> [!!!][BUGFIX] Require cuyz/valinor ^0.12.0

- src/Error/ErrorHandler.php
- tests/src/Error/ErrorHandlerTest.php
With this PR, mapping errors occurred during config parsing are now handled in the `ErrorHandler`. That means, all available mapping error messages are now passed to the user.
> [FEATURE] Properly handle config mapping errors in `ErrorHandler`

- composer.json
- tests/src/Error/ErrorHandlerTest.php
This PR adds support for recently published version `0.13.0` of `cuyz/valinor` and following patch releases.
> [FEATURE] Add support for cuyz/valinor ^0.13.0

- .github/workflows/tests.yaml
This PR enables tests for the upcoming `2.4` release of Composer in the test matrix.
> [TASK] Include Composer 2.4 in test matrix

- .github/dependabot.yml
This PR adds additional support for Composer updates managed by Dependabot.
> [TASK] Enable Dependabot updates for Composer

- resources/config.schema.json
- src/Builder/Config/ConfigFactory.php
- src/Builder/Config/ConfigReader.php
- src/Exception/InvalidConfigurationException.php
- src/Resource/Local/Composer.php
- tests/src/Builder/Config/ConfigFactoryTest.php
- tests/src/Builder/Config/ConfigReaderTest.php
- tests/src/Builder/Generator/GeneratorTest.php
- tests/src/Builder/Generator/Step/InstallComposerDependenciesStepTest.php
- tests/src/Builder/Generator/Step/ProcessSharedSourceFilesStepTest.php
- tests/src/Builder/Generator/Step/ProcessSourceFilesStepTest.php
- tests/src/ContainerAwareTestCase.php
- tests/src/Fixtures/Files/config.json
- tests/src/Fixtures/Files/invalid-template/composer.json
- tests/src/Fixtures/Files/invalid-template/config.json
- tests/src/Fixtures/Files/invalid-template/config.yaml
- tests/src/Fixtures/Templates/json-template/config.json
- tests/src/Fixtures/Templates/yaml-template/config.yaml
With this PR, the Composer package name of a project builder template repository is now used as identifier. The `identifier` property provided with the template configuration is now deprecated and will no longer be respected.
> [!!!][FEATURE] Deprecate config identifier and use Composer name instead

- tests/src/Builder/Generator/Step/ProcessSharedSourceFilesStepTest.php
It seems like there was some copy-pasta when the `ProcessSharedSourceFilesStepTest` class was generated. The test is now fixed and correct subject and assertions are applied.
> [BUGFIX] Use correct subject and assertions in test

- resources/config.schema.json
- src/Builder/Generator/Step/ProcessingFilesTrait.php
- tests/src/Builder/Config/ConfigFactoryTest.php
- tests/src/Builder/Generator/Step/ProcessSharedSourceFilesStepTest.php
- tests/src/Builder/Generator/Step/ProcessSourceFilesStepTest.php
- tests/src/Fixtures/Templates/json-template/config.json
- tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy-3.yaml
- tests/src/Fixtures/Templates/json-template/templates/src/dummy-3.json
- tests/src/Fixtures/Templates/yaml-template/config.yaml
- tests/src/Fixtures/Templates/yaml-template/templates/shared/shared-dummy-3.yaml
- tests/src/Fixtures/Templates/yaml-template/templates/src/dummy-3.yaml
With this PR, paths in file conditions of configured steps are now tested against `fnmatch`. This allows to include supported symbols such as `*` or `.`.
> [FEATURE] Support `fnmatch` symbols in step's file condition paths

- composer.json
- composer.lock
This PR adds support for `cuyz/valinor` versions 0.15.x and 0.16.x.
> [FEATURE] Add support for cuyz/valinor 0.15.x and 0.16.x

- resources/config.schema.json
- src/Builder/Config/ValueObject/Property.php
- src/Builder/Generator/Step/CollectBuildInstructionsStep.php
- tests/src/Builder/Config/ConfigFactoryTest.php
- tests/src/Builder/Config/ValueObject/PropertyTest.php
- tests/src/ContainerAwareTestCase.php
- tests/src/Fixtures/Templates/json-template/config.json
- tests/src/Fixtures/Templates/yaml-template/config.yaml
With this PR, first-level configuration properties can now be conditional. That means, whole sections can be left out when collecting build instructions, based on the given condition.
For example, the following configuration leaves out the second section in case the sub-property of the first section is answered with "yes":
```diff
{
// ...
"properties": [
{
"identifier": "first",
"name": "First section",
"properties": [
{
"identifier": "continue",
"name": "Continue with second section?",
"type": "question"
}
]
},
{
"identifier": "second",
"name": "Second question",
+           "if": "first['continue']",
"properties": [
{
"identifier": "done",
"name": "Well done!",
"type": "staticValue",
"defaultValue": "Hello world"
}
]
}
]
}
```
> [FEATURE] Add support for conditional properties

- composer.json
- composer.lock
- phpstan.neon
- src/Resource/Local/Composer.php
- tests/src/Twig/Func/PhpVersionFunctionTest.php
With this PR, we now use the PHPStan extension installer to ease integration of third-party PHPStan extensions.
> [TASK] Use PHPStan extension installer

- composer.json
- composer.lock
- src/Error/ErrorHandler.php
Valinor 1.0.0 was released and we're upgrading to the codebase to fully support the stable version. Support for older versions is dropped.
Resolves: #43
> [!!!][FEATURE] Upgrade to `cuyz/valinor` 1.0.0

- Dockerfile
`donatj/mock-webserver` requires `ext-socket` to be installed. Therefore, we must install this PHP extension in `Dockerfile` to satisfy this requirement.
> [BUGFIX] Satisfy PHP extension requirements in Dockerfile

- Dockerfile
Since this library already supports Composer 2.4, we can safely upgrade to this version in the Dockerfile as well.
> [TASK] Upgrade to Composer 2.4 in Dockerfile

- src/Resource/Http/PhpApiClient.php
- tests/src/Resource/Http/PhpApiClientTest.php
In case the latest stable PHP version for a given branch cannot be determined with the php.net API, we now handle this situation by falling back to the dot-zero release.
This is especially needed for unreleased version branches, e.g. PHP 8.2, which now results in `8.2.0`.
> [BUGFIX] Fall back to dot-zero release if PHP version cannot be determined

- composer.json
- composer.lock
- phpstan.neon
- src/IO/InputReader.php
This PR is based on the great article [_How to Measure Your Type Coverage_](https://tomasvotruba.com/blog/how-to-measure-your-type-coverage/) by Tomas Votruba. It introduces type coverage measurement for PHPStan, targeting a minimum of 99% type coverage.
> [FEATURE] Measure type coverage within PHPStan

- src/Bootstrap.php
- src/Exception/UnsupportedEnvironmentException.php
When running project creation in an outdated environment, it might happen that exceptions occur, e.g. when accessing the `InstalledVersions` class. This class differs between Composer versions, e.g. classes generated with Composer 2.0 miss some required methods.
As Composer loads this class from the global installation – if present – there's no integrity check in place.
Therefore, we're now extending the bootstrapping by an additional check whether the loaded `InstalledVersions` class meets our requirements.
If not, an exception is thrown guiding the user through the required steps to make the environment compatible.
A better approach would be to get rid of the `InstalledVersions` class. Sadly, this is not a valuable solution at the moment, since we're very dependent on information …
> [BUGFIX] Exit early if current environment is unsupported

- tests/src/Builder/Generator/GeneratorTest.php
- tests/src/Builder/Generator/Step/InstallComposerDependenciesStepTest.php
- tests/src/ClearableBufferIO.php
- tests/src/ContainerAwareTestCase.php
- tests/src/Template/Provider/BaseComposerProviderTest.php
- tests/src/Twig/RendererTest.php
The stored output within the global IO must not be available in other test cases than the current one. Therefore, we now clear the output on each `tearDown()`, resetting the internal state as required.
> [BUGFIX] Isolate global IO state from other test cases

- installer/composer.json.twig
- src/Exception/InvalidTemplateSourceException.php
- src/Template/Provider/BaseComposerProvider.php
- src/Template/TemplateSource.php
- tests/src/Template/Provider/BaseComposerProviderTest.php
This PR extends the integration of template packages. It is now possible to optionally provide a version constraint used to install a selected template package. This is especially useful when requesting a more legacy version of a template package, which was by now not possible since we let Composer decide to select a compatible version on its own.
> [FEATURE] Allow specifying template package version constraint

- src/Builder/Config/ConfigFactory.php
- src/Builder/Config/ConfigReader.php
This PR streamlines handling of the project root path to make the library act as expected across the whole codebase. Only two implementations are left out:
* `Bootstrap::simulateCreateProject()`: In this case, we must explicitly reference the current codebase rather than calculating any path to make sure the simulation is based on the correct (probably uncommitted) files.
* `Helper\FilesystemHelper::getProjectRootPath()`: In this case, the `dirname(__DIR__, 2)` acts only as last resort in case root path calculation has failed in all previous steps (determination via env variable and from `Composer\InstalledVersions`).
Resolves: #62
> [BUGFIX] Streamline usage of project root paths

- .github/dependabot.yml
We can safely use Dependabot's automatic versioning strategy for Composer, since the test workflow already tests for compatibility with supported environments.
> [BUGFIX] Use Dependabot's automatic versioning strategy

- config/services.yaml
- docs/architecture.md
- src/Bootstrap.php
- src/Console/Application.php
- src/Console/Simulation.php
- tests/src/ClearableBufferIO.php
- tests/src/Console/ApplicationTest.php
- tests/src/ContainerAwareTestCase.php
- tests/src/Fixtures/DummyProvider.php
With this PR, the actual application logic is decoupled from the bootstrapping component. This makes it possible to better test the application logic in an isolated scope, separating it from the actual environment construction which is already available in testing context.
Additionally, the application simulation logic is moved to a separate class.
> [TASK] Decouple application logic from bootstrapping

- src/Bootstrap.php
- src/Exception/InvalidTemplateSourceException.php
- src/IO/Messenger.php
- src/Template/Provider/BaseComposerProvider.php
- src/Template/Provider/CustomComposerProvider.php
- src/Template/Provider/PackagistProvider.php
- src/Template/Provider/ProviderInterface.php
- tests/src/Console/ApplicationTest.php
- tests/src/Fixtures/DummyComposerProvider.php
- tests/src/Fixtures/DummyProvider.php
This PR addresses the second part of the https://github.com/CPS-IT/project-builder/issues/57 where a default template source provider (in this case Packagist) is now selected. Packages are automatically fetched from this provider and are suggested to the user. This will allow first-time users to quickly get started. More experienced users are still given the opportunity to define a custom registry (and with #53 a VCS provider).
- The status information (when fetching packages from a provider) is now showing the URL making it a bit cleary to users where the project builder attempts to fetch template packages from.
> [FEATURE] Set Packagist as default provider and auto-fetch template sources

- installer/composer.json.twig
- src/Template/Provider/BaseComposerProvider.php
- src/Template/TemplateSource.php
- tests/src/Template/Provider/BaseComposerProviderTest.php
- tests/src/Template/TemplateSourceTest.php
With #61, usage of template package version constraints was introduced. However, if one omits specifying a custom version constraint, the default constraint (= latest version) is not always properly applied, e.g. if the requested package is already cached globally by Composer. This PR assures the expected behavior.
> [BUGFIX] Properly handle latest version constraint

- installer/composer.json.twig
Since #61, a custom constraint can be configured during template installation. However, this is not fully supported for constraints with stability lower than "stable", e.g. branches or RCs. This PR defines a minimum-stability "dev" along with installation preference "stable" to solve this issue.
> [BUGFIX] Allow using constraints with minimum stability "dev"

- .github/workflows/tests.yaml
Composer 2.5 was released and we should continuously test its compatibility with the project builder. Therefore, it is now included in the test matrix.
> [TASK] Include Composer 2.5 in test matrix

- src/Builder/Generator/Step/CollectBuildInstructionsStep.php
- tests/src/Builder/Generator/Step/CollectBuildInstructionsStepTest.php
When properties or sub-properties are skipped (that is, a configured `if` condition evaluates to `false`), they can no longer be referenced in other conditions. That leads to an error when accessing those properties:
> Undefined array key "xyz"
As a result, the whole project generation process fails.
To circumvent this behavior, `null` is now always used as default value in case the property or sub-property was skipped.
> [BUGFIX] Avoid errors when accessing skipped properties

- tests/src/ClearableBufferIO.php
The output stream is now properly cleared via `ftruncate` instead of `fflush`.
> [BUGFIX] Properly truncate IO stream in tests

- tests/src/ClearableBufferIO.php
- tests/src/ContainerAwareTestCase.php
The IO was never completely reset between test cases. Instead, only the output stream was cleared. With this PR, both input and output streams are now correctly re-initialized with their initial state.
> [BUGFIX] Properly reset IO between test cases

- .github/workflows/cgl.yaml
- CONTRIBUTING.md
- composer.json
This PR introduces a new Composer script `validate-schema`. It can be used to validate the configured JSON schema and is already added to the CGL workflow.
> [TASK] Validate JSON schema in CGL workflow

- docs/processing-build-steps.md
The initial pre-released version of this package contained an `InteractiveStepInterface`. When this interface got removed, the appropriate documentation was left. This is now cleaned up.
> [DOCS] Remove all mentions of interactive steps

- docs/configuration.md
- installer/composer.json.twig
Template packages may now define version constraints for compatible versions of the project builder in their `composer.json`:
```diff
{
"name": "cpsit/project-builder-template-my-fancy-project",
"type": "project-builder-template",
+    "require": {
+        "cpsit/project-builder": "^1.0"
+    }
// ...
}
```
The `cpsit/project-builder` dependency is replaced during installation of the template package, thus no additional vendor files will be downloaded. Instead, Composer is now able to better distinguish between compatible versions of the project builder and requested template packages.
> [FEATURE] Allow specifying project builder as dependency in template packages

- src/IO/Messenger.php
The `Helper::length()` method provided by Symfony Console is way more exact in calculating string length than a plain `strlen`.
> [BUGFIX] Use Symfony Console helper to determine string length

- CONTRIBUTING.md
- installer/composer.json.twig
- src/Template/Provider/BaseProvider.php
This PR fixes a possible side effect introduced with #78 that may occur during development of this package or subsequent template packages. When working in a specific development branch, the current package version is hidden which causes template package installations to fail, especially when running `composer simulate`.
With this PR, a new environment variable `PROJECT_BUILDER_SIMULATE_VERSION` is introduced. It can be used to explicitly override the current root package version.
Example:
```bash
PROJECT_BUILDER_SIMULATE_VERSION=1.5.0 composer simulate -v
```
Resolves: #80
> [BUGFIX] Allow simulation of root package version

- .gitattributes
Both `.editorconfig` and `CONTRIBUTING.md` are not relevant in dist archives. Therefore, they're now added to `.gitattributes`.
> [TASK] Exclude several files from dist archives

- .dockerignore
- .gitattributes
Several development-only files must not reside in the final Docker image, therefore they're now ignored for `docker build`.
> [TASK] Exclude development-only files from Docker image

- src/Builder/Generator/Step/ShowNextStepsStep.php
- src/IO/Messenger.php
The `IO\Messenger::write()` method can now handle multiple messages at once. For this, the first argument now allows a list of string values:
```php
$messenger->write('foo');
$messenger->write('baz');
// equals
$messenger->write(['foo', 'baz']);
```
> [FEATURE] Allow writing multiple messages at once

- tests/src/ContainerAwareTestCase.php
The mock handler queue must be cleared on tear down, otherwise tests can not be isolated properly from each other.
> [BUGFIX] Reset mock handler queue between test scenarios

- docs/architecture.md
- src/IO/InputReader.php
- tests/src/IO/InputReaderTest.php
This PR introduces a new `IO\InputReader::hiddenValue()` method. It can be used to obtain sensitive user input, being hidden to the current IO.
> [FEATURE] Introduce input reader option for hidden input

- docs/architecture.md
- src/Exception/MisconfiguredValidatorException.php
- src/IO/Validator/AbstractValidator.php
- src/IO/Validator/CallbackValidator.php
- src/IO/Validator/EmailValidator.php
- src/IO/Validator/NotEmptyValidator.php
- src/IO/Validator/UrlValidator.php
- src/Template/Provider/BaseProvider.php
- tests/src/Builder/Config/ValueObject/FileConditionTest.php
- tests/src/Builder/Config/ValueObject/PropertyOptionTest.php
- tests/src/Builder/Config/ValueObject/PropertyValidatorTest.php
- tests/src/Fixtures/ModifyingValidator.php
- tests/src/IO/Validator/CallbackValidatorTest.php
- tests/src/Template/Provider/BaseProviderTest.php
Version constraints for selected template packages are now validated with Composer's `VersionParser`. In case an invalid version constraint was entered, the user can now enter another constraint (or leave it empty to let Composer decide on the version itself). For this, a new `CallbackValidator` was introduced.
> [FEATURE] Validate package version constraint

- .github/workflows/release.yaml
The @cpsitgmbh user may create releases in the future using our organization-wide release token :pray:
> [TASK] Use release token in GitHub release job

- src/Resource/Local/Git.php
If [include files](https://git-scm.com/docs/git-config#_includes) are configured in the global `.gitconfig` file, they should be respected when reading Git configuration. This is now done by passing the [`--includes`](https://git-scm.com/docs/git-config#Documentation/git-config.txt---no-includes) option.
> [BUGFIX] Respect include files when reading Git configuration

- src/Template/Provider/BaseProvider.php
This code snippet causes much confusion to codecov, since sometimes it's covered and sometimes it isn't. Since we cannot rely on that code being covered, we can safely ignore it from code coverage.
> [BUGFIX] Ignore uncoverable code from code coverage

- .github/workflows/tests.yaml
- CONTRIBUTING.md
- composer.json
- tests/docker/docker-build.sh
This PR adds a test suite to test the correct behavior of the distributed Docker image. The test suite can be started in two ways:
* Run `composer test` to execute all tests (Unit tests + Docker tests)
* Run `composer test:docker` to execute only Docker tests
At the moment, the test suite only tests whether the image can be built and run in non-TTY mode. Thus, it checks whether to exit early with a warning about the current non-interactive environment. More tests may be added in the future.
> **Note** The Composer scripts for Unit tests have been renamed:
> 
> * `composer test` → `composer test:unit`
> * `composer test:coverage` → `composer test:unit:coverage`
> [TASK] Introduce Docker test suite

- Dockerfile
The `ext-sockets` platform requirement is a dependency of the dev-requirement `donatj/mock-webserver`. Since dev-requirements are not installed in the docker container, we can safely ignore this requirement.
> [BUGFIX] Ignore ext-sockets platform req in docker image

- composer.json
- composer.lock
- src/IO/Messenger.php
- src/Template/Provider/BaseProvider.php
- tests/src/Template/Provider/BaseProviderTest.php
The actually installed template version is now shown in the template source installation progress. As a side effect, this fixes a bug where the wrong template version was dumped in the template artifact.
> [FEATURE] Show resolved template version in install progress

- CONTRIBUTING.md
- README.md
- docs/conf.py
This PR updates the documentation url to the new domain: https://project-builder.cps-it.de/
> [DOCS] Update documentation url

- .github/workflows/cgl.yaml
Since PHP-CS-Fixer now officially supports PHP 8.2, we can safely remove the introduced compatibility flag.
:bulb: This partially reverts commit cbe2ab5941f586cf1627b7411fb9f4c604b15e45.
> [TASK] Remove PHP_CS_FIXER_IGNORE_ENV compatibility flag

- src/Helper/ArrayHelper.php
- tests/src/Helper/ArrayHelperTest.php
The `getValueByPath` and `setValueByPath` utility methods in `ArrayHelper` only support arrays and objects of `ArrayObject`. However, the types were not written as such. That's why they're hardened now to improve type-safety. In addition, some more test cases were added to cover all relevant side-effects of those methods.
> [BUGFIX] Improve type-safety of utility methods in ArrayHelper

- resources/config.schema.json
- src/Builder/Config/ConfigFactory.php
- tests/src/Fixtures/Templates/json-template/config.json
- tests/src/Fixtures/Templates/yaml-template/config.yaml
This PR extends the config schema to allow `$schema` properties in config files. This is especially helpful when developing custom template packages since most IDEs understand the `$schema` property and can therefore provide autocompletion for template configuration. Internally, the `$schema` property is unset during config parsing as it's not relevant for the project builder.
> [TASK] Allow $schema property in config files

- docs/development/architecture/components.md
- resources/config.schema.json
- src/IO/Validator/RegexValidator.php
- tests/src/IO/Validator/RegexValidatorTest.php
- tests/src/IO/Validator/ValidatorFactoryTest.php
This PR introduces a new `RegexValidator`. It can be used to validate a given input against a regular expression. The regular expression must be configured through validator option `pattern`. In addition, a custom error message can be configured by using validator option `errorMessage`. If omitted, a default error message is used.
Resolves: #151
> [FEATURE] Introduce RegexValidator

- docs/development/configuration.md
- resources/config.schema.json
- src/Builder/Config/ValueObject/FileCondition.php
- tests/src/Builder/Config/ConfigFactoryTest.php
- tests/src/Fixtures/Templates/json-template/config.json
- tests/src/Fixtures/Templates/yaml-template/config.yaml
This PR extends the config JSON schema to no longer require a `if` condition to be set for file conditions in case a `target` path is configured.
Example:
```diff
steps:
- type: processSourceFiles
options:
fileConditions:
- path: 'source-dir/*'
-          if: 'true'
target: 'target-dir/*'
```
💡 If no `target` path is configured, an `if` condition is still required.
> [FEATURE] Loosen requirement for "if" condition if "target" is set

- src/IO/InputReader.php
- tests/src/IO/InputReaderTest.php
When using optional multi-select fields, it should be possible to omit a selection. Prior to this PR, the InputReader threw an exception in this case, which should never happen.
> [BUGFIX] Properly handle no selection for optional multi-select fields

- src/Bootstrap.php
The check for legacy/unsupported environments is currently not called early enough. This leads to the same issues as before. Thus, the check is now moved to an earlier position, making it available as early as possible.
> [BUGFIX] Perform legacy environment check as early as possible

- tests/src/Template/Provider/ComposerProviderTest.php
- tests/src/Template/Provider/VcsProviderTest.php
Calling `ReflectionProperty::setAccessible()` has no effect since PHP 8.1.0. Thus, it can be safely removed.
> [BUGFIX] Avoid usage of `ReflectionProperty::setAccessible()`

- src/Builder/Generator/Generator.php
- src/IO/Messenger.php
- tests/src/Builder/Generator/GeneratorTest.php
- tests/src/Console/ApplicationTest.php
- tests/src/IO/MessengerTest.php
When a project generation step fails, the whole process fails due to a thrown `StepFailureException`. This can be very frustrating, because the whole process needs to be restarted from scratch.
For this, exceptions thrown during project generation are now caught and the user can decide whether he wants to restart project generation or not. If not, project generation is aborted like before.
> [BUGFIX] Allow restarting project generation on step failure

- config/services.yaml
- src/IO/Console/TraceableConsoleIO.php
- src/IO/Messenger.php
- src/Template/Provider/BaseProvider.php
- src/Template/Provider/ComposerProvider.php
- src/Template/Provider/VcsProvider.php
- tests/src/BufferedConsoleOutput.php
- tests/src/IO/Console/TraceableConsoleIOTest.php
- tests/src/Template/Provider/ComposerProviderTest.php
- tests/src/Template/Provider/VcsProviderTest.php
This PR fixes an issue where private VCS repositories could not be used due to authentication issues. Composer itself is able to prompt for username and password in case the current is not authenticated for a given VCS repository, but this is only possible in interactive mode. Since we used a buffered output for template installation, this was not possible before. Hence, this PR switches to a console IO for such operations to circumvent authentication issues.
> [BUGFIX] Use console IO to enable probable VCS authentications

- src/IO/InputReader.php
Since `InputReader::staticValue()` always either returns a non-empty string or `null`, this can (and should) also be reflected within the annotated return types.
> [TASK] Harden return types for `InputReader::staticValue()`

- .github/workflows/cgl.yaml
- composer.json
- docs/contributing/workflow.md
This PR harmonizes the usage of CGL scripts:
- `lint` scripts no longer fix CGL issues, but only print them to the console (dry-run mode)
- `fix` scripts actually fix CGL issues (like done before with `lint:<program>:fix`)
> [TASK] Streamline `lint` and `fix` CGL scripts

- docs/development/build-steps.md
- docs/development/configuration.md
- resources/config.schema.json
- src/Builder/Config/ValueObject/StepOptions.php
- src/Builder/Generator/Step/RunCommandStep.php
- tests/src/Builder/Config/ConfigFactoryTest.php
- tests/src/Builder/Generator/GeneratorTest.php
- tests/src/Builder/Generator/Step/RunCommandStepTest.php
- tests/src/Fixtures/Templates/json-template/config.json
- tests/src/Fixtures/Templates/yaml-template/config.yaml
This PR extends the new `runCommand` step by a step option `skipConfirmation`. It defaults to `false`. When set to `true`, the user confirmation before running the configured command is skipped.
> [FEATURE] Allow to skip confirmation to run configured command

- config/services.yaml
- resources/build-artifact.schema.json
- src/Builder/Artifact/Migration/Migration.php
- src/Builder/Artifact/Migration/Migration1679497137.php
- src/Builder/ArtifactGenerator.php
- src/Builder/ArtifactReader.php
- tests/src/Fixtures/DummyMigration.php
This PR changes the logic of build artifact versioning a little bit. Artifacts are no longer versioned by incrementing the previous version. Instead, each migration provides a unique version identifier. This, in turn, is then used as version of the build artifact. In fact, the version of the latest migration represents the version of a build artifact. If a build artifact's version does not match the latest available migration version, it is automatically migrated during parsing by `ArtifactReader::fromFile()`.
> [FEATURE] Use timestamps for build artifact versions

- src/Builder/Generator/Step/GenerateBuildArtifactStep.php
- tests/src/Builder/Generator/GeneratorTest.php
- tests/src/Builder/Generator/Step/GenerateBuildArtifactStepTest.php
This PR fixes an issue with build artifacts to explicitly write them to the target directory.
> [BUGFIX] Write build artifact to target directory

- config/services.php
- docs/development/configuration.md
- docs/development/dependency-injection.md
- rector.php
- src/DependencyInjection/CompilerPass/ExpressionLanguageProviderPass.php
With this PR, custom expression function providers for Symfony Expression Language are now autoconfigured when building the service container. This allows template authors to provide custom expression functions and to use them in template configuration.
> [FEATURE] Support expression languages providers for autoconfiguration

- docs/development/configuration.md
- src/Builder/Generator/Step/CollectBuildInstructionsStep.php
- tests/src/Builder/Generator/Step/CollectBuildInstructionsStepTest.php
This PR adds support for Twig templates in the configuration option `properties.*.value`.
Example:
```yaml
properties:
- name: Foo
identifier: foo
value: '{{ "foo"|convert_case("upper") }}'
```
> [FEATURE] Render main property value as Twig template

- .github/workflows/tests.yaml
Composer 2.6 was released recently and we should make sure the project builder supports the latest version.
Resolves: #299
> [TASK] Add Composer 2.6 to test matrix

- renovate.json
This PR modifies the `renovate.json` file to use shared config presets from `CPS-IT/renovate-config` repository.
> [TASK] Use Renovate config presets from CPS config repository

- .github/workflows/docker.yaml
The workflow for Docker builds is able to be run on workflow dispatch. However, the actual job requires a tag to be set for the current execution. This check is now removed to be able to run manual Docker builds using workflow dispatch.
> [BUGFIX] Allow manual Docker builds

- .github/workflows/docker.yaml
- docs/usage/docker.md
With this PR, GitHub Container Registry is now used as an alternative provider for the Docker image.
```bash
docker run --rm -it -v <target-dir>:/app ghcr.io/cps-it/project-builder
```
> [FEATURE] Publish Docker image at GitHub Container Registry

- docs/development/configuration.md
The example used to demonstrate some basic configuration options is pretty limited. Especially when it comes to the various opportunities to define file conditions, the example is not very helpful and hard to understand for new contributors and template developers.
This PR aims to provide a better overview about possible configuration options. It introduces some new and more real-world config properties and demonstrates how to properly use them in combination with file conditions.
> [DOCS] Show more configuration options in config example

- .github/workflows/tests.yaml
This PR replaces the `satackey/action-docker-layer-caching` action by `jpribyl/action-docker-layer-caching` since the former seems to be no longer maintained (see satackey/action-docker-layer-caching#347).
> [TASK] Use up-to-date GitHub action for docker layer caching

- src/Builder/Writer/TemplateWriter.php
- tests/src/Builder/Writer/TemplateWriterTest.php
This PR fixes an edge-case issue with `TemplateWriter`: If a target file with `.twig` file extension was given, it was not removed. This only happened if the target file was calculated from the given source file. The appropriate test case did not catch this case, because it was not created from a realistic scenario. It is now fixed as well.
Resolves: #392
> [BUGFIX] Correctly remove twig file extension with target file given

- composer.json
- composer.lock
Composer < 2.7 is not and won't ever be compatible with `symfony/console` 7.x (see https://github.com/composer/composer/issues/11741#issuecomment-1847572878). An appropriate "fix" was added with Composer 2.6.6 where `symfony/console` 7.x was explicitly disallowed. Since we allow `symfony/console` 7.x in Composer environments which are most likely not compatible with said version, we now explicitly remove support for `symfony/console` 7.x. We'll re-add it later if most people have upgraded to a more recent version where stable support for `symfony/console` 7.x is guaranteed.
> [BUGFIX] Disallow symfony/console 7.x for the time being

- docs/development/build-steps.md
- docs/development/configuration.md
- resources/config.schema.json
- src/Builder/Config/ValueObject/StepOptions.php
- src/Builder/Generator/Step/RunCommandStep.php
- tests/src/Builder/Generator/Step/RunCommandStepTest.php
This PR introduces a new configuration option `allowFailures` for the `runCommand` step. It allows to continue the normal project generation process even in cases of command execution failures.
> [FEATURE] Allow commands to fail using configuration

- docs/development/configuration.md
- src/Template/Provider/BaseProvider.php
- tests/src/Template/Provider/BaseProviderTest.php
This PR adds support for a new config option `extra.cpsit/project-builder.exclude-from-listing` within template packages. It allows to exclude packages from being listed in the template package selection.
Resolves: #472
> [FEATURE] Support exclusion of template packages

- src/Template/Provider/VcsProvider.php
- tests/src/Template/Provider/VcsProviderTest.php
When explicitly requiring a template package using the VCS provider, the underlying repository should always be listed, even if it's configured to be excluded from listing using the configuration option introduced with #473.
> [BUGFIX] Ignore "exclude-from-listing" config in VCS provider

- src/Template/Provider/BaseProvider.php
- tests/src/Template/Provider/BaseProviderTest.php
- tests/src/Template/Provider/VcsProviderTest.php
This PR defines the `cache-dir` config option to disable Composer cache while searching and listing template packages. This avoids outdated package information. All other areas are not touched and still rely on Composer's internal caching behavior.
> [TASK] Disable Composer cache while searching for template packages

- Dockerfile
This PR switches from the official `composer` Docker image to the semi-official `composer/composer` image, because the latter is built more frequently. In addition, the `-bin` image variant is used which only serves as provider for the `composer` binary. This should reduce build times significantly.
> [TASK] Use composer/composer for Docker multi-stage build

- .github/workflows/tests.yaml
- Dockerfile
Composer 2.7 was released and this PR adds support for the new minor version. In addition, the Docker image was changed to use Composer 2.7 instead of 2.6.
> [FEATURE] Add support for Composer 2.7

- src/IO/Messenger.php
When documentation was restructured and deployed to https://project-builder.cps-it.de/, a referencing link was not exchanged. This is now fixed.
> [BUGFIX] Fix outdated link to documentation

- src/Bootstrap.php
- src/Console/Application.php
- src/Template/Provider/BaseProvider.php
- src/Template/Provider/VcsProvider.php
- tests/src/Template/Provider/BaseProviderTest.php
This PR fixes a regression introduced with #478. The disabled package cache is not supported by all underlying Composer operations. Therefore, this PR changes the configuration of package caches and only disables them for simulation during development. In addition, the `VcsProvider` is configured to always explicitly *enable* package cache since Git operations require caches to be active.
> [BUGFIX] Disable template source cache for simulations only

- src/Builder/Generator/Generator.php
- tests/src/Builder/Generator/GeneratorTest.php
When project generation fails, the user currently only receives the information "Project generation failed. All processed steps will be reverted.". There's currently no way to find what actually caused the project generation failure.
This PR changes error handling on project generation failure by adding the exception message on verbose output (`-v`). In addition, the exception trace will be displayed on very verbose output (`-vv`).
> [TASK] Show exception details on failure with verbose output

- docs/development/architecture/events.md
- src/Builder/Generator/Step/CollectBuildInstructionsStep.php
- src/Event/BuildInstructionCollectedEvent.php
- tests/config/services.yaml
- tests/src/Builder/Generator/GeneratorTest.php
- tests/src/Builder/Generator/Step/CollectBuildInstructionsStepTest.php
- tests/src/Event/BuildInstructionCollectedEventTest.php
This PR introduces a new `BuildInstructionCollectedEvent`. It is dispatched in `CollectBuildInstructionsStep` each time a build instruction is about to be applied to the underlying `BuildResult`. The event can be used to modify the collected value for the configured property or sub-property.
> [FEATURE] Introduce event for collected build instructions

- composer.json
This PR extends the `validate-schema` Composer script to validate all available JSON schema files.
> [TASK] Run JSON schema validation on all available JSON schemas

- src/Bootstrap.php
- src/IO/Validator/AbstractValidator.php
- src/IO/Validator/NotEmptyValidator.php
- tests/src/Helper/StringHelperTest.php
- tests/src/IO/Validator/CallbackValidatorTest.php
- tests/src/Naming/NameVariantBuilderTest.php
- tests/src/Twig/Func/NameVariantFunctionTest.php
This PR adds error identifiers to all `@phpstan-ignore-*` annotations to avoid unreported PHPStan errors.
> [TASK] Use errors identifiers in `@phpstan-ignore-*` annotations

- docs/development/configuration.md
- resources/config.schema.json
- src/Builder/Config/ValueObject/StepOptions.php
- src/Builder/Generator/Step/RunCommandStep.php
- tests/src/Builder/Generator/Step/RunCommandStepTest.php
This PR adds a new step option `required`. It can be used for the `runCommand` step to allow optional execution of the configured command. If set to `true` (default), the command **must** be executed, otherwise the step fails and further execution is stopped. If set to `false`, skipped commands no longer make the whole generation process fail (which can be seen as a bug in the current implementation) and are therefore optional.
> [FEATURE] Allow optional execution of commands in "runCommand" step

- Dockerfile
This PR switches the base Docker image from 2.7 to 2.8.
> [FEATURE] Switch to Composer 2.8 as base Docker image

- .dockerignore
- .gitattributes
- composer.json
- composer.lock
- version-bumper.yaml
New releases can now be initiated by running `composer bump-version patch` (or `major`, `minor`).
> [TASK] Use `eliashaeussler/version-bumper` plugin for new releases
